### ISSUE TITLE
Input Client id, Client Secret, etc

### ISSUE THREAD

**Issue by cansi22** [bastienboutonnet/py-nest-thermostat#5]
I don't see a way to enter the values. I see that you have an "access_token.json" in the code, but it is not in the folder and I do not know the structure that has said file.

The one thing that asks me when I install and put "py-nest devices" is the authentication url but it gives me an error

```
PS C:\Users\xxxx> py-nest devices
[21:13:40] INFO     Authenticating                                                                                            auth.py:76
Open the following URL in your browser: https://nestservices.google.com/partnerconnections//auth?redirect_uri=&access_type=offline&promp
t=consent&client_id=&response_type=code&scope=https://www.googleapis.com/auth/sdm.service
Once you have authorised, you will be redirected to your redirect_uri:
? Paste the code contained between '?code=' and '&scope=' from the URL of the page that was loaded after you authorised the app.
AuthRequestError

  Token request unsuccessful token_response.status_code=400, token_response.text='{\n  "error": "invalid_request",\n  "error_description": "Could not determine client ID from request."\n}'

  at AppData\Local\Programs\Python\Python310\lib\site-packages\py_nest_thermostat\auth.py:145 in authenticate
      141│                             # we check wether there is already an entry for "refresh_token" in the file
      142│                             # and in that case we probably want to nuke it first.
      143│                             f.write(f"refresh_token={self.refresh_token}")
      144│                 else:
    → 145│                     raise AuthRequestError(
      146│                         f"Token request unsuccessful {token_response.status_code=}, {token_response.text=}"
      147│                     )
      148│             else:
      149│                 raise AuthRequestError("You do not seem to have provided any authorization_code")
```

**Comment by bastienboutonnet** [comment]
Hey @cansi22 thanks for your interest in the project and apologies for the sheer lack of documentation on the setup. 

I'll be working on making it better some time soon, feel free to help with the README if you manage to get it working after my explanations.

So it looks like a few things are happening (or maybe not happening) so I'll check a few things before answering anything stupid.

Did you go through the set up flow where you set up and authorize your nest device following this guide: https://www.wouternieuwerth.nl/controlling-a-google-nest-thermostat-with-python/ at all?

From the output, you pasted it looks like you're trying to use `py-nest devices` to list the devices that you want to control. And judging by the URL that is generated you'd didn't provide any of the the credentials and whatnot.

So here are a few pointers:
1. the `access_token.json` will be generated automatically by the authentication process so you don't need to worry about that in theory because it will be placed in the expected location by `py-nest`.
2. what you will need to provide is a `credentials.env` file however and you should place it here in the location that the following line of code uses: https://github.com/bastienboutonnet/py-nest-thermostat/blob/main/py_nest_thermostat/auth.py#L16
3. the `credentials.json` file takes the following format:
```
client_id=<your oauth client id, should be here: https://console.cloud.google.com/apis/credentials?>
client_secret=<your oauth client secret, should be here: https://console.cloud.google.com/apis/credentials?>
project_id=<the nest project id that should be here: https://console.nest.google.com/device-access/project-list>
redirect_url=<the redirect URL you chose when setting up your OAuth credentials>
```

Once all this is in there, the authentication process should generate you a good URL that will take you through the rest of the flow and you'll want to copy the code that is contained between `'?code='` and `'&scope='`. If this doesn't work let me know and it is probably a bug.

**Important note **: I'm about to rework the authentication file shebang so you might find in a little bit that the `credentials.env` will need to be something like  `config.yaml` but the content of at least the above shouldn't change.

Also, sorry sorry for the lack of docs, I didn't think anyone would be looking to use it that early. If you feel like it feel free to help out.

By the way I build this tool mostly on twitch, so if you're inclined feel free to join us here: https://www.twitch.tv/datafrittata

**Comment by bastienboutonnet** [comment]
Hey @cansi22 not sure if you're still having issues or if you have not tried yet, but I have updated the authentication and now it uses a yaml file with a bit of a different structure. A sample of it can be found here: https://github.com/bastienboutonnet/py-nest-thermostat/blob/main/config.yaml.sample

I hope this helps. If I don't hear back, I'll probably close the issue due to lack of interest in a few days but if you still want to try and you still have issues, by all means, feel free to re-open the issue or a new one.

**Comment by bastienboutonnet** [comment]
Closed due to lack of interest. Please re-open if needed.
